# Generated by Django 5.0 on 2023-12-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='followers',
            new_name='FollowersCount',
        ),
    ]
